import type { TaskWithLimit, RawDataItem } from '../types';

// --- 常量配置 ---
export const LIMITS = { CONTRIB: 1000, CREDIT: 5000 };

// 调整后的基准参数
export const TASKS: Record<string, TaskWithLimit> = {
    HOLLOW: { id: 'hollow', name: "普通空洞", contrib: 80, credit: 600, time: 150 },
    HUNT: { id: 'hunt', name: "恶名狩猎", contrib: 100, credit: 500, time: 60 },
    EXPERT: { id: 'expert', name: "专业挑战", contrib: 70, credit: 250, time: 60 }
};

// --- 数据源 ---
export const rawData: RawDataItem[] = [
    // --- 极速档 (0-2m) ---
    { name: "雨果的心魔", time: "00:42", sec: 42, py: "yuguodexinmo", abbr: "ygdxm" },
    { name: "再见校园", time: "00:43", sec: 43, py: "zaijianxiaoyuan", abbr: "zjxy" },
    { name: "黑暗中的足迹", time: "00:50", sec: 50, py: "heianzhongdezuji", abbr: "hazdzj" },
    { name: "深度「叛变」", time: "00:51", sec: 51, py: "shendupanbian", abbr: "sdpb" },
    { name: "拯救邦布泰迪", time: "00:55", sec: 55, py: "zhengjiubangbutaidi", abbr: "zjbbtd" },
    { name: "御猫出巡", time: "00:56", sec: 56, py: "yumaochuxun", abbr: "ymcx" },
    { name: "猫鼠异位", time: "00:57", sec: 57, py: "maoshuyiwei", abbr: "msyw" },
    { name: "有些团子的保质期是永远", time: "01:00", sec: 60, py: "youxietuanzidebaozhiqishiyongyuan", abbr: "yxtzdbzqsyy" },
    { name: "死路直通车", time: "01:04", sec: 64, py: "siluzhitongche", abbr: "slztc" },
    { name: "因缘之战", time: "01:05", sec: 65, py: "yinyuanzhizhan", abbr: "yyzz" },
    { name: "休眠体回收计划", time: "01:06", sec: 66, py: "xiumiantihuishoujihua", abbr: "xmthsjhua" },
    { name: "兔与绳", time: "01:08", sec: 68, py: "tuyusheng", abbr: "tys" },
    { name: "一种循环", time: "01:10", sec: 70, py: "yizhongxunhuan", abbr: "yzxh" },
    { name: "以身作局", time: "01:13", sec: 73, py: "yishenzuoju", abbr: "yszj" },
    { name: "高报酬的指名委托", time: "01:15", sec: 75, py: "gaobaochoudezhimingweituo", abbr: "gbcdzmwt" },
    { name: "好事发生", time: "01:15", sec: 75, py: "haoshifasheng", abbr: "hsfs" },
    { name: "火爆末班车", time: "01:17", sec: 77, py: "huobaomobanche", abbr: "hbmbc" },
    { name: "有福共享", time: "01:18", sec: 78, py: "youfugongxiang", abbr: "yfgx" },
    { name: "舞步上行", time: "01:18", sec: 78, py: "wubushangxing", abbr: "wbsx" },
    { name: "昔日锋芒", time: "01:18", sec: 78, py: "xirifengmang", abbr: "xrfm" },
    { name: "战场寻踪", time: "01:19", sec: 79, py: "zhanchangxunzong", abbr: "zcxz" },
    { name: "以假乱真的测试", time: "01:19", sec: 79, py: "yijialuanzhendeceshi", abbr: "yjlzdcs" },
    { name: "逃出生天", time: "01:19", sec: 79, py: "taochushengtian", abbr: "tcst" },
    { name: "诡异的来信", time: "01:20", sec: 80, py: "guiyidelaixin", abbr: "gydlx" },
    { name: "盲目的寻踪", time: "01:22", sec: 82, py: "mangmudexunzong", abbr: "mmdxz" },
    { name: "溯源", time: "01:24", sec: 84, py: "suyuan", abbr: "sy" },
    { name: "「贼猫」捉贼", time: "01:27", sec: 87, py: "zeimaozhuozei", abbr: "zmzz" },
    { name: "杀意的邀约", time: "01:32", sec: 92, py: "shayideyaoyue", abbr: "sydyy" },
    { name: "隐形帮手", time: "01:33", sec: 93, py: "yinxingbangshou", abbr: "yxbs" },
    { name: "于雨夜穿透脏腑", time: "01:35", sec: 95, py: "yuyuyechuantouzangfu", abbr: "yyyctzf" },
    { name: "重返校园", time: "01:37", sec: 97, py: "zhongfanxiaoyuan", abbr: "zfxy" },
    { name: "烈拳对峙", time: "01:38", sec: 98, py: "liequanduizhi", abbr: "lqdz" },
    { name: "稍等，信号不好", time: "01:38", sec: 98, py: "shaodengxinhaobuhao", abbr: "sdxhbh" },
    { name: "洞中谍", time: "01:39", sec: 99, py: "dongzhongdie", abbr: "dzd" },
    { name: "危险使命", time: "01:45", sec: 105, py: "weixianshiming", abbr: "wxsm" },
    { name: "牲鬼核心", time: "01:48", sec: 108, py: "shengguihexin", abbr: "sghx" },
    { name: "以真乱假", time: "01:50", sec: 110, py: "yizhenluanjia", abbr: "yzlj" },
    { name: "拯救大黑客芮恩", time: "01:52", sec: 112, py: "zhengjiudaheikeruien", abbr: "zjdhkra" },
    { name: "急中生智的自救", time: "01:55", sec: 115, py: "jizhongshengzhidezijiu", abbr: "jzszdzj" },
    // --- 普通档 (2-4m) ---
    { name: "盗窃者与守护者", time: "02:00", sec: 120, py: "daoqiezheyushouhuzhe", abbr: "dqzyshz" },
    { name: "未完成事项", time: "02:00", sec: 120, py: "weiwanchengshixiang", abbr: "wwcsx" },
    { name: "小小大失控", time: "02:00", sec: 120, py: "xiaoxiaodashikong", abbr: "xxdsk" },
    { name: "甩开跟踪", time: "02:04", sec: 124, py: "shuaikaigenzong", abbr: "skgz" },
    { name: "绳与兔", time: "02:04", sec: 124, py: "shengyutu", abbr: "syt" },
    { name: "称颂与空洞", time: "02:06", sec: 126, py: "chengsongyukongdong", abbr: "csykd" },
    { name: "机性的爱", time: "02:08", sec: 128, py: "jixingdeai", abbr: "jxda" },
    { name: "疾速追机", time: "02:18", sec: 138, py: "jisuzhuiji", abbr: "jszj" },
    { name: "紧急救援2", time: "02:18", sec: 138, py: "jinjijiuyuan2", abbr: "jjjy2" },
    { name: "背叛与否的终点", time: "02:19", sec: 139, py: "beipanyufoudezhongdian", abbr: "bpyfdzd" },
    { name: "格莉丝的「弗兰肯斯坦」", time: "02:24", sec: 144, py: "gelisidefulankensitan", abbr: "glsdflkst" },
    { name: "兄弟！要出发了！", time: "02:25", sec: 145, py: "xiongdiyaochufale", abbr: "xdycfl" },
    { name: "绳之道III", time: "02:28", sec: 148, py: "shengzhidao3", abbr: "szd3" },
    { name: "绳之道II", time: "02:31", sec: 151, py: "shengzhidao2", abbr: "szd2" },
    { name: "以身试险的觉悟", time: "02:42", sec: 162, py: "yishenshixiandejuewu", abbr: "yssxdjw" },
    { name: "以弱胜强的技巧", time: "02:48", sec: 168, py: "yiruoshengqiangdejiqiao", abbr: "yrsqdjq" },
    { name: "追本溯源", time: "02:55", sec: 175, py: "zhuibensuyuan", abbr: "zbsy" },
    { name: "「魔女」审判", time: "02:59", sec: 179, py: "monvushenpan", abbr: "mnsp" },
    { name: "捷足先登的买手", time: "03:05", sec: 185, py: "jiezuxiandengdemaishou", abbr: "jzxdnms" },
    { name: "逃生早鸟票", time: "03:13", sec: 193, py: "taoshengzaoniaopiao", abbr: "tsznp" },
    { name: "以微知著的真心", time: "03:14", sec: 194, py: "yiweizhizhudezhenxin", abbr: "ywzzdzx" },
    { name: "歌声是星环闪耀", time: "03:15", sec: 195, py: "geshengshixinghuanlanyao", abbr: "gssxhsy" },
    { name: "意想不到的挑战", time: "03:40", sec: 220, py: "yixiangbudaodetiaozhan", abbr: "yxbddtz" },
    { name: "欺骗者与背叛者", time: "03:43", sec: 223, py: "qipianzheyubeipanzhe", abbr: "qpzybzz" },
    { name: "失踪的证人", time: "03:58", sec: 238, py: "shizongdezhengren", abbr: "szdzr" },
    { name: "绳之道IV", time: "03:59", sec: 239, py: "shengzhidao4", abbr: "szd4" },
    // --- 久坐档 (>4m) ---
    { name: "烈拳困斗", time: "04:00", sec: 240, py: "liequankundou", abbr: "lqkd" },
    { name: "绳之道I", time: "04:00", sec: 240, py: "shengzhidao1", abbr: "szd1" },
    { name: "紧急追捕", time: "04:01", sec: 241, py: "jinjizhuibu", abbr: "jjzb" },
    { name: "如获新生", time: "04:20", sec: 260, py: "ruhuoxinsheng", abbr: "rhxs" },
    { name: "宿命的重逢", time: "04:48", sec: 288, py: "sumingdechongfeng", abbr: "smdcf" },
    { name: "英雄诞生的骑行", time: "04:53", sec: 293, py: "yingxiongdanshengdeqixing", abbr: "yxdxdqx" },
    { name: "诅咒，礼物和爱", time: "05:33", sec: 333, py: "zuzhouliwuheai", abbr: "zzlwha" },
    { name: "业与劫", time: "06:40", sec: 400, py: "yeyujie", abbr: "yyj" },
    { name: "空洞奇妙日", time: "06:46", sec: 406, py: "kongdongqimiaori", abbr: "kdqmr" },
    { name: "谁在深渊中凝望", time: "07:55", sec: 475, py: "shuizaishenyuanzhongningwang", abbr: "szsyznw" },
];
